apiVersion: v1
kind: Secret
metadata:
  name: mindbox-app-secret
  namespace: mindbox-sre-test
  labels:
    app: mindbox-app
type: Opaque
data:
  # Баз64 закодированные значения (в реальности должны быть зашифрованы)
  # echo -n "mindbox-secret-key" | base64
  SECRET_KEY: bWluZGJveC1zZWNyZXQta2V5
  
  # echo -n "mindbox-api-token" | base64
  API_TOKEN: bWluZGJveC1hcGktdG9rZW4= 